[Fix] Support CPython version < 3.9
alibaba/code-data-share-for-python pull request #12
Opened 2022-05-07 03:14 UTC by imzhuhl

Summary: Support CPython version 3.8; Adjust the tuple depth in file `test_share_object.py` to prevent parser stack overflow; Fix `PyCDS_Table_Get`.

Test Plan: -

Reviewed-by: -

Issue: #4

[<tag>] <One-line description of the patch>

Summary: <detailed description of the change>

Test Plan: <how this patch has been tested>

Reviewed-by: <Github IDs of reviewers>

Issue: <full URL or #github_tag>

2022-05-07 03:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/code-data-share-for-python?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/code-data-share-for-python?pullRequest=12) before we can accept your contribution.<br/><hr/>**Honglin Zhu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/code-data-share-for-python?pullRequest=12) it.</sub>

2022-05-07 15:01 UTC, oraluben requested changes

2022-05-08 13:51 UTC, imzhuhl commented on tests/test_cds_extension/test_share_object.py
> +        for i in range(70):
ok

2022-05-08 13:59 UTC, imzhuhl commented on src/_cds/lookup_table.h
> +#define IS_LINKED_LIST 1
Ok, the new commit already implements this.

2022-05-09 05:04 UTC, oraluben approved these changes
LGTM

2022-05-09 05:38 UTC, merged